require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- Disabled nvim-cmp temporarily because it's not working well with Github copilot
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
-- require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.dashboard"
require "user.whichkey"
require "user.autocommands"
require "user.molokai"
require "user.notify"
require "user.startify"
require "user.silicon"
require "user.git"
-- require "user.symbols-outline"
require "user.urlview"
require "user.rust-tools"
require "user.aerial"
require "user.transparent"
require "user.filetype"
require "user.smart-splits"

require "user.myerlang"
